# One of ['unicycle', 'pointturn']
RRT_TYPE: 'unicycle'

# Path to png file representing 2D map. White pixels are navigable, gray/black are not.
# A path of '' indicates that habitat_sim will be used instead.
PNG_FILE: ''

# habitat_sim parameters
JSON_GZ: 'path/to/scene_name.json.gz'
SCENES_DIR: 'path/to/scenes_dir/'

# -1 means generate trees for all episode IDs in the json.gz file
# Otherwise, only generate a tree for the designated episode_id
EPISODE_ID: -1

# Where visualizations and json files (where trees are stored) are saved
OUT_DIR: 'example_map'

# Radius of the agent, which will shrink the navigable space
# Note: Agent is assumed to be cylindrical
AGENT_RADIUS: 0.2

MAX_LINEAR_VELOCITY: 0.25 # in meters per second
MAX_ANGULAR_VELOCITY: 30.0 # in degrees per second
BACKWARDS_ALLOWED: False
NEAR_THRESHOLD: 1.5 # in meters
MAX_DISTANCE: 1.5 # in meters

# Whether to show the visualizations using cv2.imshow
VISUALIZE_ON_SCREEN: False

# Number of nodes to generate for tree
ITERATIONS: 5e3

# How often jsons/visualizations should be saved
VISUALIZE_ITERATIONS: 500